language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cdbs fakeroot

script: dpkg-buildpackage -us -uc -rfakeroot

deploy:
  provider: releases
  api_key: 
    secure: "c6857ece6d4b9bec839c58c27b052df37ad0f7df"
  file_glob: true
  overwrite: true
  draft: true
  file: 
    - "../libpluxx*.deb"
    - "../libpluxx*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
