language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cdbs fakeroot

script: dpkg-buildpackage -us -uc -rfakeroot

deploy:
  provider: releases
  file_glob: true
  overwrite: true
  draft: true
  file: 
    - "../libpluxx*.deb"
    - "../libpluxx*.tar.gz"
  skip_cleanup: true
  on:
    tags: false
